# Generated by Django 3.1.3 on 2020-12-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, verbose_name=' nomi')),
                ('slug', models.SlugField(help_text="Kalit so'z", max_length=75, unique=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'lar',
                'ordering': ['-id'],
            },
        ),
    ]
