# Generated by Django 3.1.3 on 2020-12-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201209_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': "User ma'lumot", 'verbose_name_plural': "User ma'lumotlari"},
        ),
    ]
