# Generated by Django 3.1.3 on 2020-12-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
