# Generated by Django 3.1.4 on 2021-02-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210207_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
